package com.mcd.model;

public class RequestIP {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestip.ID
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestip.ip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestip.boolvalue
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    private Boolean boolvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requestip.tag
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestip.ID
     *
     * @return the value of requestip.ID
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestip.ID
     *
     * @param id the value for requestip.ID
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestip.ip
     *
     * @return the value of requestip.ip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestip.ip
     *
     * @param ip the value for requestip.ip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestip.boolvalue
     *
     * @return the value of requestip.boolvalue
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    public Boolean getBoolvalue() {
        return boolvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestip.boolvalue
     *
     * @param boolvalue the value for requestip.boolvalue
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    public void setBoolvalue(Boolean boolvalue) {
        this.boolvalue = boolvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requestip.tag
     *
     * @return the value of requestip.tag
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requestip.tag
     *
     * @param tag the value for requestip.tag
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}