package com.mcd.mapper;

import com.mcd.model.RequestIP;
import com.mcd.model.RequestIPExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RequestIPMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    long countByExample(RequestIPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    int deleteByExample(RequestIPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    int insert(RequestIP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    int insertSelective(RequestIP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    List<RequestIP> selectByExampleWithRowbounds(RequestIPExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    List<RequestIP> selectByExample(RequestIPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    RequestIP selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") RequestIP record, @Param("example") RequestIPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    int updateByExample(@Param("record") RequestIP record, @Param("example") RequestIPExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    int updateByPrimaryKeySelective(RequestIP record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requestip
     *
     * @mbg.generated Fri May 22 23:24:15 CST 2020
     */
    int updateByPrimaryKey(RequestIP record);
}